name: "网关最佳实战"
env: "dev"
runMode: "debug"

mysql:
  user: "root"
  password: "123456"
  ip: "127.0.0.1"
  port: 3366
  db: "imooc"
  parameter: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  server: "127.0.0.1:6379"
  password: ""